
package edu.agh.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddControllerService", targetNamespace = "http://controllers/", wsdlLocation = "http://localhost:8080/Students-ejb/add?wsdl")
public class AddControllerService
    extends Service
{

    private final static URL ADDCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDCONTROLLERSERVICE_EXCEPTION;
    private final static QName ADDCONTROLLERSERVICE_QNAME = new QName("http://controllers/", "AddControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Students-ejb/add?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDCONTROLLERSERVICE_WSDL_LOCATION = url;
        ADDCONTROLLERSERVICE_EXCEPTION = e;
    }

    public AddControllerService() {
        super(__getWsdlLocation(), ADDCONTROLLERSERVICE_QNAME);
    }

    public AddControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDCONTROLLERSERVICE_QNAME, features);
    }

    public AddControllerService(URL wsdlLocation) {
        super(wsdlLocation, ADDCONTROLLERSERVICE_QNAME);
    }

    public AddControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDCONTROLLERSERVICE_QNAME, features);
    }

    public AddControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddController
     */
    @WebEndpoint(name = "AddControllerPort")
    public AddController getAddControllerPort() {
        return super.getPort(new QName("http://controllers/", "AddControllerPort"), AddController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddController
     */
    @WebEndpoint(name = "AddControllerPort")
    public AddController getAddControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllers/", "AddControllerPort"), AddController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDCONTROLLERSERVICE_EXCEPTION!= null) {
            throw ADDCONTROLLERSERVICE_EXCEPTION;
        }
        return ADDCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
