
package edu.agh.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Base64_EncoderService", targetNamespace = "http://file_encoders/", wsdlLocation = "http://localhost:8080/Students-ejb/file?wsdl")
public class Base64EncoderService
    extends Service
{

    private final static URL BASE64ENCODERSERVICE_WSDL_LOCATION;
    private final static WebServiceException BASE64ENCODERSERVICE_EXCEPTION;
    private final static QName BASE64ENCODERSERVICE_QNAME = new QName("http://file_encoders/", "Base64_EncoderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Students-ejb/file?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASE64ENCODERSERVICE_WSDL_LOCATION = url;
        BASE64ENCODERSERVICE_EXCEPTION = e;
    }

    public Base64EncoderService() {
        super(__getWsdlLocation(), BASE64ENCODERSERVICE_QNAME);
    }

    public Base64EncoderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASE64ENCODERSERVICE_QNAME, features);
    }

    public Base64EncoderService(URL wsdlLocation) {
        super(wsdlLocation, BASE64ENCODERSERVICE_QNAME);
    }

    public Base64EncoderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASE64ENCODERSERVICE_QNAME, features);
    }

    public Base64EncoderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Base64EncoderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Base64Encoder
     */
    @WebEndpoint(name = "Base64_EncoderPort")
    public Base64Encoder getBase64EncoderPort() {
        return super.getPort(new QName("http://file_encoders/", "Base64_EncoderPort"), Base64Encoder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Base64Encoder
     */
    @WebEndpoint(name = "Base64_EncoderPort")
    public Base64Encoder getBase64EncoderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://file_encoders/", "Base64_EncoderPort"), Base64Encoder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASE64ENCODERSERVICE_EXCEPTION!= null) {
            throw BASE64ENCODERSERVICE_EXCEPTION;
        }
        return BASE64ENCODERSERVICE_WSDL_LOCATION;
    }

}
