
package edu.agh.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Base64_Encoder", targetNamespace = "http://file_encoders/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Base64Encoder {


    /**
     * 
     * @param path
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Send", targetNamespace = "http://file_encoders/", className = "edu.agh.soa.Send")
    @ResponseWrapper(localName = "SendResponse", targetNamespace = "http://file_encoders/", className = "edu.agh.soa.SendResponse")
    public String send(
        @WebParam(name = "path", targetNamespace = "")
        String path);

    /**
     * 
     * @param path
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByte", targetNamespace = "http://file_encoders/", className = "edu.agh.soa.GetByte")
    @ResponseWrapper(localName = "getByteResponse", targetNamespace = "http://file_encoders/", className = "edu.agh.soa.GetByteResponse")
    public byte[] getByte(
        @WebParam(name = "path", targetNamespace = "")
        String path);

}
