
package edu.agh.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImageControllerService", targetNamespace = "http://controllers/", wsdlLocation = "http://localhost:8080/Students-ejb/image?wsdl")
public class ImageControllerService
    extends Service
{

    private final static URL IMAGECONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGECONTROLLERSERVICE_EXCEPTION;
    private final static QName IMAGECONTROLLERSERVICE_QNAME = new QName("http://controllers/", "ImageControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Students-ejb/image?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGECONTROLLERSERVICE_WSDL_LOCATION = url;
        IMAGECONTROLLERSERVICE_EXCEPTION = e;
    }

    public ImageControllerService() {
        super(__getWsdlLocation(), IMAGECONTROLLERSERVICE_QNAME);
    }

    public ImageControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGECONTROLLERSERVICE_QNAME, features);
    }

    public ImageControllerService(URL wsdlLocation) {
        super(wsdlLocation, IMAGECONTROLLERSERVICE_QNAME);
    }

    public ImageControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGECONTROLLERSERVICE_QNAME, features);
    }

    public ImageControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImageController
     */
    @WebEndpoint(name = "ImageControllerPort")
    public ImageController getImageControllerPort() {
        return super.getPort(new QName("http://controllers/", "ImageControllerPort"), ImageController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageController
     */
    @WebEndpoint(name = "ImageControllerPort")
    public ImageController getImageControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllers/", "ImageControllerPort"), ImageController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGECONTROLLERSERVICE_EXCEPTION!= null) {
            throw IMAGECONTROLLERSERVICE_EXCEPTION;
        }
        return IMAGECONTROLLERSERVICE_WSDL_LOCATION;
    }

}
