
package edu.agh.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RemoveControllerService", targetNamespace = "http://controllers/", wsdlLocation = "http://localhost:8080/Students-ejb/remove?wsdl")
public class RemoveControllerService
    extends Service
{

    private final static URL REMOVECONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException REMOVECONTROLLERSERVICE_EXCEPTION;
    private final static QName REMOVECONTROLLERSERVICE_QNAME = new QName("http://controllers/", "RemoveControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Students-ejb/remove?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMOVECONTROLLERSERVICE_WSDL_LOCATION = url;
        REMOVECONTROLLERSERVICE_EXCEPTION = e;
    }

    public RemoveControllerService() {
        super(__getWsdlLocation(), REMOVECONTROLLERSERVICE_QNAME);
    }

    public RemoveControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMOVECONTROLLERSERVICE_QNAME, features);
    }

    public RemoveControllerService(URL wsdlLocation) {
        super(wsdlLocation, REMOVECONTROLLERSERVICE_QNAME);
    }

    public RemoveControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMOVECONTROLLERSERVICE_QNAME, features);
    }

    public RemoveControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoveControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RemoveController
     */
    @WebEndpoint(name = "RemoveControllerPort")
    public RemoveController getRemoveControllerPort() {
        return super.getPort(new QName("http://controllers/", "RemoveControllerPort"), RemoveController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RemoveController
     */
    @WebEndpoint(name = "RemoveControllerPort")
    public RemoveController getRemoveControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controllers/", "RemoveControllerPort"), RemoveController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REMOVECONTROLLERSERVICE_EXCEPTION!= null) {
            throw REMOVECONTROLLERSERVICE_EXCEPTION;
        }
        return REMOVECONTROLLERSERVICE_WSDL_LOCATION;
    }

}
